### ISSUE TITLE
WARN: Could not create table env_dashboard.

### ISSUE THREAD

**Issue by rvcoutinho** [vipinsthename/environment-dashboard#132]
Receiving "WARN: Could not create table env_dashboard." after jenkins upgrade. Already re-installed the plugin with no success.

Jenkins version: 2.7.1.

**Comment by kramos** [comment]
Hi @rvcoutinho if you are happy to purge the data that might help - either by the red button, or by deleting the db file which from memory will be in the Jenkins home directory.

I must say I'm not sure if @vipinsthename planning to make any more updates to this.  Personally I'm getting more into Hygieia as well which via the Jenkins plugin (which isn't yet published) does similar things albeit in a more complex way.

**Comment by rvcoutinho** [comment]
I just removed de db files a couple of hours ago and it works again. Thank you!
