### ISSUE TITLE
Gradle Job DSL Build fails - environmentDashboard cannot be resolved

### ISSUE THREAD

**Issue by wykapedia** [vipinsthename/environment-dashboard#136]
`Exception in thread "main" javaposse.jobdsl.dsl.DslScriptException: (xxx, line 1658) No signature of method: javaposse.jobdsl.dsl.helpers.wrapper.WrapperContext.environmentDashboard() is applicable for argument types: xxx`

This exception appears when trying to generate jobs with the ob DSL plugin.  The following has been added to the build.gradle:

`provided 'org.jenkins-ci.plugins:environment-dashboard:1.1.7@jar'`

The groovy script is unable to compile with the following code:

`
environmentDashboard {
                        environmentName(envName)
                        componentName(componentName)
                        buildNumber('${PIPELINE_VERSION}')
                        buildJob("deploy")
                        packageName(packageName)
                        addColumns(true)
                        column("Docker Image", dockerImage)
                        column("URL", url)
}
`

**Comment by Sam123ben** [comment]
Any idea how we can troubleshoot this issue. I wish to run the dashboard using the jenkinsfile.

I did as mentioned in the document but still facing the below issue:

java.lang.NoSuchMethodError: No such DSL method 'environmentDashboard' found among steps [VersionNumber, addBadge, addErrorBadge, addHtmlBadge, addInfoBadge, addShortText, addWarningBadge, ansiColor, ansiblePlaybook, ansibleVault, approveReceivedEvent, approveRequestedEvent, archive, artifactPromotion,

**Comment by Sam123ben** [comment]
Also if I create a freestyle job and then try to convert it to a pipeline I could not because// Powered by Infostretch 

timestamps {

node () {

// Unable to convert a build step referring to "org.jenkinsci.plugins.environmentdashboard.DashboardBuilder". Please verify and convert manually if required.
}
} of the below:

**Comment by willwh** [comment]
See #150
