### ISSUE TITLE
I am not able to run the jenkinsfile to run the dashboard after installing it

### ISSUE THREAD

**Issue by Sam123ben** [vipinsthename/environment-dashboard#146]
Hi Team,

I am getting the below issue when trying to build the dashboard job from the jenkinsfile. Any help please.

My configuration:

        stage('Create the environment for the users to know what is deployed to where') {

            try {
                environmentDashboard {
                    environmentName("${namespace}")
                    componentName('om-thor')
                    productVersion("${thorBuildVersion}")
                    buildJob("${env.JOB_NAME}")
                    addColumns(true)
                    columns('Envs', "${namespace}")
                }
            } catch (Exception ex) {
                println "Automation failed while trying to create the env dashboard"
                slackSend channel: "#orchprotos-build-fail", color: '#439FE0', message: "Build ${BUILD_NUMBER} Failed on ${BUILD_TIMESTAMP} via ${JOB_NAME} at stage: 'Injecting the datas to'"
                currentBuild.result = 'FAILURE'
                integerationStatus = "Fail"
                throw new RuntimeException("The injecting of the datas to the env dashboard failed... Operation is aborted!; ${ex}")
            }

        }

Getting below error:

[BFA] Scanning build for known causes...
[BFA] No failure causes found
[BFA] Done. 0s
java.lang.NoSuchMethodError: No such DSL method 'environmentDashboard' found among steps [VersionNumber, addBadge, addErrorBadge, addHtmlBadge, addInfoBadge, addShortText, addWarningBadge, ansiColor, ansiblePlaybook, ansibleVault, approveReceivedEvent, approveRequestedEvent, archive, artifactPromotion, awaitDeploymentCompletion, awsIdentity, bat, bayesianAnalysis, bitbucketStatusNotify, build, buildImage, catchError, cfInvalidate, cfnCreateChangeSet, cfnDelete, cfnDeleteStackSet, cfnDescribe, cfnExecuteChangeSet, cfnExports, cfnUpdate, cfnUpdateStackSet, cfnValidate, checkout, container, containerLog, createEnvironment, createEvent, createSummary, currentNamespace, deleteDir, deployAPI, dir, dockerFingerprintFrom, dockerFingerprintRun, dockerNode, ec2, ec2ShareAmi, echo, ecrLogin, emailext, emailextrecipients, envVarsForTool, error, fileExists, findFiles, getContext, git, gitChangelog, hubot, hubotApprove, hubotProject, inNamespace, inSession, input, invokeLambda, isUnix, jiraAddComment, jiraAddWatcher, jiraAssignIssue, jiraAssignableUserSearch, jiraComment, jiraDeleteAttachment, jiraDeleteIssueLink, jiraDeleteIssueRemoteLink, jiraDeleteIssueRemoteLinks, jiraDownloadAttachment, jiraEditComment, jiraEditComponent, jiraEditIssue, jiraEditVersion, jiraGetAttachmentInfo, jiraGetComment, jiraGetComments, jiraGetComponent, jiraGetComponentIssueCount, jiraGetFields, jiraGetIssue, jiraGetIssueLink, jiraGetIssueLinkTypes, jiraGetIssueRemoteLink, jiraGetIssueRemoteLinks, jiraGetIssueTransitions, jiraGetIssueWatches, jiraGetProject,

**Comment by Aft3rm4thx** [comment]
This is associated with PR #135 that is currently open and has been open for over a year.  Once this merges in, environmentDashboard method should be implemented and usable.

**Comment by willwh** [comment]
Please see #150
