### ISSUE TITLE
Request for transfer of Environment Dashboard Plugin's ownership

### ISSUE THREAD

**Issue by mominkhan** [vipinsthename/environment-dashboard#147]
Hi @vipinsthename ,

Hope you are well.

There are some PRs for the environment dashboard plugin which are pending for a long time.

If you are not actively maintaining this plugin, could you please provide your consent to get the ownership transferred to someone in the community. This consent is required by the Jenkins Developers Group to take the necessary actions.

Best Regards,
Momin

**Comment by terrafying** [comment]
Is there some kind of transfer protocol for when a user goes dark?  I've also tried to get in contact with him a few months ago.

**Comment by mominkhan** [comment]
Request for putting up this plugin for adoption has been raised here with Jenkins Dev team.
Link: [https://groups.google.com/forum/?nomobile=true#!topic/jenkinsci-dev/v-BqyE4F9RM](https://groups.google.com/forum/?nomobile=true#!topic/jenkinsci-dev/v-BqyE4F9RM)

If somebody is interested in adopting this plugin, then they can track and respond to the request raised with the Jenkisn Dev team in google groups.

Thanks.

Regards,
Momin

**Comment by willwh** [comment]
I've been added as a contributor by @vipinsthename and I'm starting to triage issues, and clean up the plugin. Please see #150 

We have plans to get this moved in to the `jenkinsci` github group, please see: https://issues.jenkins-ci.org/browse/HOSTING-808
