### ISSUE TITLE
[FR] would be great to have multiple dashboards

### ISSUE THREAD

**Issue by singha24** [vipinsthename/environment-dashboard#154]
not an issue, but a feature request

**Comment by jarst** [comment]
What do you mean by `multiple dashboards` ?
Is anything stopping you from adding more than one Dashboard views in Jenkins UI?

**Comment by willwh** [comment]
environment-dashboard does support multiple dashboards:

- Create a New View
- Select the type as "Environment Dashboard"
- Assign new environment dashboard config to jobs appropriately
