### ISSUE TITLE
Blank column name

### ISSUE THREAD

**Issue by kramos** [vipinsthename/environment-dashboard#22]
Hi @mmcgarr 

Custom columns are clever.  One minor issue: you can add empty custom column names on the job configure page (in Add Custom Columns).  These then cause the dashboard to fail to update:

Pre-Build Update: WARN: Could not alter table env_dashboard to add column .

It shouldn't be possible to save empty custom columns.

**Comment by mmcgarr** [comment]
Hi @kramos, thanks for finding this. 

You're right, this was overlooked - I'll make a fix and try get this in by the end of the week. 

Thanks.
